import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ポートフォリオ OrionBranch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
          <h1 className={styles.title}>
            Orion Branch
          </h1>
        </div>
        <div className={styles.about}>
          <a href='/about'>
            <h1 className={styles.title}>
              About
            </h1>
          </a>
        </div>
        <div className={styles.news}>
          <a href='/news'>
            <h1 className={styles.title}>
              News
            </h1>
          </a>
        </div>
        <div className={styles.contact}>
          <a href="mailto:">
            <h1 className={styles.title}>
              Contact
            </h1>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
          <span className={styles.logo}>
            <small>©2022 OrionBranch</small>
          </span>
      </footer>
    </div>
  )
}
